### ISSUE TITLE
The app doesn't work(Search Location Branch)

### ISSUE THREAD

**Issue by AlanTso** [hello-paulvin/flutter-tutorial-showcase#1]
Hi, 

Thanks for sharing. I also face the same problem as you had in the Youtube channel. However, my network connection is very good. Can you still use the App now?
I/flutter (30711): PlatformException(IO_ERROR, A network error occurred trying to lookup the address ''., null, null)
I/Choreographer(30711): Skipped 3 frames!  The application may be doing too much work on its main thread.
I/flutter (30711): PlatformException(IO_ERROR, A network error occurred trying to lookup the address ''., null, null)
I/Choreographer(30711): Skipped 2 frames!  The application may be doing too much work on its main thread.
I/flutter (30711): PlatformException(IO_ERROR, A network error occurred trying to lookup the address ''., null, null)

Cheers,
Alan

**Comment by edemekong** [comment]
Hello Alan, it feels you're working on the search location branch. I will have a look. Then give you feedback.

**Comment by edemekong** [comment]
![Screenshot 2021-04-20 004211](https://user-images.githubusercontent.com/68385854/115316495-63a3fd00-a171-11eb-9584-2c2d0b2adbfe.png)
Here is an example, everything is quite working well.

**Comment by edemekong** [comment]
This error is cause by wrong inputed location address or bad internet.

> PlatformException(IO_ERROR, A network error occurred trying to lookup the address ''., null, null)

**Comment by edemekong** [comment]
And this i cause by this error: PlatformException(IO_ERROR, A network error occurred trying to lookup the address ''., null, null)
> What this means is that your code is taking long to process and frames are being skipped because of it, It maybe because of some heavy processing that you are doing at the heart of your application or DB access or any other thing which causes the thread to stop for a while.

> Skipped 3 frames! The application may be doing too much work on its main thread.

**Comment by edemekong** [comment]
Hope this is cleared?
I'm closing the issue. Feel free to reopen.
